development:
  adapter: postgresql
  encoding: unicode
  database: atlas
  pool: 2
  username: oski
  password: Postgres123

production:
  adapter: postgresql
  encoding: unicode
  database: atlas
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>